name: Update subconverter

on:
  schedule:
    - cron: 0 */12 * * *
   
jobs:
  Build:
    name: Build and Update
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Prepare
      run: |
        rm -rf subconverter
        git clone https://github.com/tindy2013/subconverter.git
    - name: Build
      run: docker run -v $GITHUB_WORKSPACE/subconverter:/root/workdir multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
    - name: Clean up
      run: |
        mkdir temp
        mv -f subconverter/subconverter/* temp/
        sudo chattr -R -i subconverter
        sudo rm -rf subconverter
        mv -f temp subconverter
        mv -f subconverter/subconverter subconverter/subconverter.exe
        sudo chmod +x subconverter/subconverter.exe
    - name: Modify pref.ini
      run: |
        sudo cp -rf files/* subconverter/
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        author_name: GitHub Action
        author_email: noreply@github.com
        message: "Update subconverter"
        add: "-A"
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }} 
